### ISSUE TITLE
Error: socket hang up

### ISSUE THREAD

**Issue by iamzfj** [andris9/simplesmtp#95]
Error: socket hang up
    at SecurePair.error (tls.js:1013:23)
    at EncryptedStream.CryptoStream._done (tls.js:705:22)
    at CleartextStream.read [as _read] (tls.js:496:24)
    at CleartextStream.Readable.read (_stream_readable.js:320:10)
    at EncryptedStream.onCryptoStreamFinish (tls.js:301:47)
    at EncryptedStream.g (events.js:180:16)
    at EncryptedStream.EventEmitter.emit (events.js:92:17)
    at finishMaybe (_stream_writable.js:354:12)
    at endWritable (_stream_writable.js:361:3)
    at EncryptedStream.Writable.end (_stream_writable.js:339:5)
    at EncryptedStream.CryptoStream.end (tls.js:643:31)

i think in

SMTPClient.prototype._destroy = function() {
    if (this._destroyed) {
        return;
    }
    this._destroyed = true;
    this._ignoreData = true;
    this.emit('end');
    this.removeAllListeners();
    // keep the error handler around, just in case
    this.socket.on('error', this._onError.bind(this));
};

you removeAllListeners,but in

SMTPClient.prototype._onError = function(err, type, data) {
    if (type && type != 'Error') {
        err.name = type;
    }
    if (data) {
        err.data = data;
    }
    err.stage = this.stage;
    this.emit('error', err);
    this.close();
};

would still emit eror so

you should add 
  this._destroyed = true;
in _onError  maybe!

**Comment by andris9** [comment]
simplesmtp is deprecated in favor of [smtp-connection](https://www.npmjs.com/package/smtp-connection), I'm not developing it anymore.
